#!/usr/bin/env bash
# Nginx server to have a custom 404 page

sudo apt-get update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '/server_name _;/a \location \/ {\n         try_files \$uri \$uri\/ =404;\n    }\n\n    error_page 404 \/404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
