#!/usr/bin/env bash
# load balancer

#shellcheck disable=SC2181
if [ $? -ne 0 ]; then
	sudo apt-get update -y -qq && \
		sudo apt-get install -y "$1" -qq
		echo -e "\n"
fi

install haproxy

sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend clickviral-tech-frontend
    bind *:80
    default_backend clickviral-tech-backend

backend clickviral-tech-backend
    balance roundrobin
    server 150523-web-01 18.210.18.234:80 check
    server 150523-web-02 18.207.140.24:80 check
"

# shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
