#!/usr/bin/env bash
# Bash script

echo "$$" > /var/run/myscript.pid

i=5
while ((i>1))
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'rm /var/run/myscript.pid' SIGQUIT
done
