#!/usr/bin/env bash
#  Bash script that loops from 1 to 20
i=0
while ((i<20))
do
	case $i in

		3)
			echo $((i+1))
			echo "bad luck from China"
			;;

		8)
			echo $((i+1))
			echo "bad luck from Japan"
			;;
		16)
			echo $((i+1))
			echo "bad luck from Italy"
			;;
		*)
			echo $((i+1))
			;;
	esac
		
	((i++))
done 
