#!/usr/bin/env bash
#  Bash script that displays the
# time for 12 hours and 59 minutes

i=0
n=1
while ((i<13))
do
	echo "Hour: " $i

	while ((n<60))
	do
		echo $n
		((n++))
	done
	n=1
	((i++))
done 
