#!/usr/bin/env bash
#  Bash script that loops from 1 to 10

FILE=./school
if [ -f "$FILE" ] || [ -d "$FILE" ]; then
	echo "school file exists"
	if [ -s "${FILE}" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$FILE" ]; then
		echo "school is a regular file"
	fi
else 
	echo "school file does not exist"
fi

